import type { BreedOption } from '@/types'

export const MOCK_BREEDS: BreedOption[] = [
  { id: 'dog-mixed', species: 'dog', nameZh: '米克斯犬', nameEn: 'Mixed Breed Dog', aliases: ['混種犬', '米克斯'], registrySources: ['custom'], group: 'Mixed', size: 'unknown', coatType: ['varies'], groomingTags: ['依實際毛型評估'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 1 },
  { id: 'dog-unknown', species: 'dog', nameZh: '未知犬種', nameEn: 'Unknown Dog Breed', aliases: ['其他犬種'], registrySources: ['custom'], group: 'Unknown', size: 'unknown', coatType: ['varies'], groomingTags: ['需現場評估'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 2 },
  { id: 'dog-shiba-inu', species: 'dog', nameZh: '柴犬', nameEn: 'Shiba Inu', aliases: ['Shiba', '日本柴犬'], registrySources: ['AKC', 'FCI'], group: 'Spitz and Primitive', size: 'small', coatType: ['double', 'short'], groomingTags: ['換毛期大量掉毛', '雙層毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 20 },
  { id: 'dog-poodle-toy', species: 'dog', nameZh: '玩具貴賓犬', nameEn: 'Poodle (Toy)', aliases: ['Toy Poodle', '貴賓', '貴婦犬'], registrySources: ['AKC', 'FCI'], group: 'Companion and Toy', size: 'toy', coatType: ['curly'], groomingTags: ['需定期修剪', '易打結'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 21 },
  { id: 'dog-poodle-miniature', species: 'dog', nameZh: '迷你貴賓犬', nameEn: 'Poodle (Miniature)', aliases: ['Miniature Poodle', '貴賓', '貴婦犬'], registrySources: ['AKC', 'FCI'], group: 'Companion and Toy', size: 'small', coatType: ['curly'], groomingTags: ['需定期修剪', '易打結'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 22 },
  { id: 'dog-poodle-standard', species: 'dog', nameZh: '標準貴賓犬', nameEn: 'Poodle (Standard)', aliases: ['Standard Poodle', '貴賓', '貴婦犬'], registrySources: ['AKC', 'FCI'], group: 'Companion and Toy', size: 'large', coatType: ['curly'], groomingTags: ['需定期修剪', '易打結'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 23 },
  { id: 'dog-maltese', species: 'dog', nameZh: '馬爾濟斯', nameEn: 'Maltese', aliases: [], registrySources: ['AKC', 'FCI'], group: 'Companion and Toy', size: 'toy', coatType: ['long', 'silky'], groomingTags: ['易打結', '需眼周清潔'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 24 },
  { id: 'dog-pomeranian', species: 'dog', nameZh: '博美犬', nameEn: 'Pomeranian', aliases: ['Pom'], registrySources: ['AKC', 'FCI'], group: 'Spitz and Primitive', size: 'toy', coatType: ['double', 'long'], groomingTags: ['雙層毛', '換毛期大量掉毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 25 },
  { id: 'dog-chihuahua', species: 'dog', nameZh: '吉娃娃', nameEn: 'Chihuahua', aliases: [], registrySources: ['AKC', 'FCI'], group: 'Companion and Toy', size: 'toy', coatType: ['short', 'long'], groomingTags: ['小型犬需輕柔操作'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 26 },
  { id: 'dog-yorkshire-terrier', species: 'dog', nameZh: '約克夏', nameEn: 'Yorkshire Terrier', aliases: ['Yorkie', '約克夏㹴'], registrySources: ['AKC', 'FCI'], group: 'Terrier', size: 'toy', coatType: ['long', 'silky'], groomingTags: ['易打結', '需定期修剪'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 27 },
  { id: 'dog-corgi-pembroke', species: 'dog', nameZh: '威爾斯柯基犬', nameEn: 'Pembroke Welsh Corgi', aliases: ['柯基'], registrySources: ['AKC', 'FCI'], group: 'Herding', size: 'medium', coatType: ['double', 'medium'], groomingTags: ['雙層毛', '換毛期大量掉毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 28 },
  { id: 'dog-french-bulldog', species: 'dog', nameZh: '法國鬥牛犬', nameEn: 'French Bulldog', aliases: ['法鬥', 'Frenchie'], registrySources: ['AKC', 'FCI'], group: 'Companion and Toy', size: 'small', coatType: ['short'], groomingTags: ['皺褶清潔', '短鼻犬注意散熱'], vetRiskTags: ['短吻呼吸道'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 30 },
  { id: 'dog-golden-retriever', species: 'dog', nameZh: '黃金獵犬', nameEn: 'Golden Retriever', aliases: ['金毛'], registrySources: ['AKC', 'FCI'], group: 'Retriever', size: 'large', coatType: ['double', 'medium'], groomingTags: ['雙層毛', '換毛期大量掉毛'], vetRiskTags: ['髖關節'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 33 },
  { id: 'dog-labrador-retriever', species: 'dog', nameZh: '拉布拉多', nameEn: 'Labrador Retriever', aliases: ['拉不拉多', 'Lab'], registrySources: ['AKC', 'FCI'], group: 'Retriever', size: 'large', coatType: ['double', 'short'], groomingTags: ['換毛期大量掉毛'], vetRiskTags: ['髖關節'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 34 },
  { id: 'dog-border-collie', species: 'dog', nameZh: '邊境牧羊犬', nameEn: 'Border Collie', aliases: ['邊牧'], registrySources: ['AKC', 'FCI'], group: 'Herding', size: 'medium', coatType: ['double', 'medium'], groomingTags: ['雙層毛', '需梳理'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 35 },
  { id: 'dog-siberian-husky', species: 'dog', nameZh: '西伯利亞哈士奇', nameEn: 'Siberian Husky', aliases: ['哈士奇'], registrySources: ['AKC', 'FCI'], group: 'Spitz and Primitive', size: 'large', coatType: ['double', 'medium'], groomingTags: ['雙層毛', '換毛期大量掉毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 37 },
  { id: 'dog-taiwan-dog', species: 'dog', nameZh: '台灣犬', nameEn: 'Taiwan Dog', aliases: ['台灣土狗', 'Formosan Mountain Dog'], registrySources: ['AKC', 'FCI'], group: 'Spitz and Primitive', size: 'medium', coatType: ['short'], groomingTags: ['短毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 45 },
  { id: 'dog-american-pit-bull-terrier', species: 'dog', nameZh: '美國比特鬥牛㹴', nameEn: 'American Pit Bull Terrier', aliases: ['比特犬', 'Pit Bull'], registrySources: ['custom'], group: 'Terrier', size: 'medium', coatType: ['short'], groomingTags: ['短毛'], vetRiskTags: [], legalStatusTw: 'prohibited', legalNote: '台灣公告比特犬及其混種犬類禁止飼養、輸入或輸出；既有個案需依主管機關規定。', sortOrder: 901 },

  { id: 'cat-mixed', species: 'cat', nameZh: '米克斯貓', nameEn: 'Domestic Mixed Cat', aliases: ['混種貓', '家貓'], registrySources: ['custom'], group: 'Mixed', size: 'unknown', coatType: ['varies'], groomingTags: ['依實際毛型評估'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 1 },
  { id: 'cat-unknown', species: 'cat', nameZh: '未知貓種', nameEn: 'Unknown Cat Breed', aliases: ['其他貓種'], registrySources: ['custom'], group: 'Unknown', size: 'unknown', coatType: ['varies'], groomingTags: ['需現場評估'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 2 },
  { id: 'cat-british-shorthair', species: 'cat', nameZh: '英國短毛貓', nameEn: 'British Shorthair', aliases: ['英短'], registrySources: ['TICA', 'CFA'], group: 'Shorthair', size: 'medium', coatType: ['short', 'dense'], groomingTags: ['短毛', '易掉毛'], vetRiskTags: ['肥厚性心肌病'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 20 },
  { id: 'cat-american-shorthair', species: 'cat', nameZh: '美國短毛貓', nameEn: 'American Shorthair', aliases: ['美短'], registrySources: ['TICA', 'CFA'], group: 'Shorthair', size: 'medium', coatType: ['short'], groomingTags: ['短毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 21 },
  { id: 'cat-scottish-fold', species: 'cat', nameZh: '蘇格蘭摺耳貓', nameEn: 'Scottish Fold', aliases: ['折耳貓', '摺耳'], registrySources: ['TICA', 'CFA'], group: 'Shorthair/Longhair', size: 'medium', coatType: ['short', 'long'], groomingTags: ['依毛型評估'], vetRiskTags: ['軟骨發育不全', '關節'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 22 },
  { id: 'cat-persian', species: 'cat', nameZh: '波斯貓', nameEn: 'Persian', aliases: [], registrySources: ['TICA', 'CFA'], group: 'Longhair', size: 'medium', coatType: ['long'], groomingTags: ['長毛', '易打結', '需眼周清潔'], vetRiskTags: ['短吻呼吸道', '眼睛'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 23 },
  { id: 'cat-exotic-shorthair', species: 'cat', nameZh: '異國短毛貓', nameEn: 'Exotic Shorthair', aliases: ['加菲貓'], registrySources: ['TICA', 'CFA'], group: 'Shorthair', size: 'medium', coatType: ['short', 'dense'], groomingTags: ['短毛', '需眼周清潔'], vetRiskTags: ['短吻呼吸道', '眼睛'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 24 },
  { id: 'cat-ragdoll', species: 'cat', nameZh: '布偶貓', nameEn: 'Ragdoll', aliases: [], registrySources: ['TICA', 'CFA'], group: 'Longhair', size: 'large', coatType: ['semi-long', 'long'], groomingTags: ['長毛', '易打結'], vetRiskTags: ['肥厚性心肌病'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 25 },
  { id: 'cat-maine-coon', species: 'cat', nameZh: '緬因貓', nameEn: 'Maine Coon', aliases: [], registrySources: ['TICA', 'CFA'], group: 'Longhair', size: 'large', coatType: ['semi-long', 'long'], groomingTags: ['長毛', '需梳理'], vetRiskTags: ['肥厚性心肌病', '髖關節'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 26 },
  { id: 'cat-russian-blue', species: 'cat', nameZh: '俄羅斯藍貓', nameEn: 'Russian Blue', aliases: ['俄藍'], registrySources: ['TICA', 'CFA'], group: 'Shorthair', size: 'medium', coatType: ['short', 'dense'], groomingTags: ['短毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 27 },
  { id: 'cat-siamese', species: 'cat', nameZh: '暹羅貓', nameEn: 'Siamese', aliases: [], registrySources: ['TICA', 'CFA'], group: 'Oriental', size: 'medium', coatType: ['short'], groomingTags: ['短毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 28 },
  { id: 'cat-bengal', species: 'cat', nameZh: '孟加拉貓', nameEn: 'Bengal', aliases: [], registrySources: ['TICA', 'CFA'], group: 'Shorthair', size: 'medium', coatType: ['short'], groomingTags: ['短毛'], vetRiskTags: [], legalStatusTw: 'allowed', legalNote: null, sortOrder: 29 },
  { id: 'cat-sphynx', species: 'cat', nameZh: '加拿大無毛貓', nameEn: 'Sphynx', aliases: ['斯芬克斯貓', '無毛貓'], registrySources: ['TICA', 'CFA'], group: 'Hairless', size: 'medium', coatType: ['hairless'], groomingTags: ['皮膚清潔', '注意保暖'], vetRiskTags: ['皮膚'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 30 },
  { id: 'cat-munchkin', species: 'cat', nameZh: '曼赤肯貓', nameEn: 'Munchkin', aliases: ['短腿貓'], registrySources: ['TICA'], group: 'Shorthair/Longhair', size: 'small', coatType: ['short', 'long'], groomingTags: ['依毛型評估'], vetRiskTags: ['骨骼關節'], legalStatusTw: 'allowed', legalNote: null, sortOrder: 31 },
]

export function getMockBreeds(species?: 'dog' | 'cat') {
  return MOCK_BREEDS
    .filter(breed => !species || breed.species === species)
    .sort((a, b) => a.sortOrder - b.sortOrder || a.nameZh.localeCompare(b.nameZh, 'zh-Hant'))
}
